function authorBooksV3(slug){return DATA.works.filter(w=>authorSlugs(w).includes(slug))}
function authorBioV3(a){if(a?.shortBio)return a.shortBio;if(Array.isArray(a?.bio)&&a.bio.length)return a.bio[0];if(typeof a?.bio==='string')return a.bio;return 'Autor publicado pelo Grupo Ediouro.'}
function authorAllBioV3(a){if(Array.isArray(a?.bio))return a.bio.filter(Boolean);if(typeof a?.bio==='string'&&a.bio.trim())return [a.bio];return a?.shortBio?[a.shortBio]:[]}
function authorImprintsV3(books){const counts={};books.forEach(w=>{if(w.imprint)counts[w.imprint]=(counts[w.imprint]||0)+1});return Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([slug,count])=>({slug,count,im:I[slug]})).filter(x=>x.im)}
function authorSeriesV3(books){return [...new Map(books.filter(w=>w.series&&S[w.series]).map(w=>[w.series,S[w.series]])).values()]}
function authorPostsV3(books){const slugs=new Set(books.map(w=>w.slug));return POSTS.filter(p=>(p.relatedWorks||[]).some(x=>slugs.has(x)))}
function authorLatestV3(books){return [...books].sort((a,b)=>{const ad=(ED[a.slug]||[]).map(e=>e.publicationDate||'').sort().reverse()[0]||'';const bd=(ED[b.slug]||[]).map(e=>e.publicationDate||'').sort().reverse()[0]||'';return bd.localeCompare(ad)})}
function filterAuthorsV3(v){const q=(v||'').trim().toLowerCase();document.querySelectorAll('.author-directory-card').forEach(el=>{el.style.display=!q||el.dataset.search.includes(q)?'grid':'none'});document.querySelectorAll('.author-letter-block').forEach(block=>{const visible=[...block.querySelectorAll('.author-directory-card')].some(el=>el.style.display!=='none');block.style.display=visible?'grid':'none'})}
function authorsList(){const list=DATA.contributors.filter(c=>c.roles?.includes('autor')).sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'));const scored=list.map(a=>({a,books:authorBooksV3(a.slug)})).sort((x,y)=>y.books.length-x.books.length||x.a.name.localeCompare(y.a.name,'pt-BR'));const featured=scored.filter(x=>x.books.length).slice(0,5);const letters=[...new Set(list.map(a=>a.name?.[0]?.toUpperCase()).filter(Boolean))];return `<main>
<section class="authors-v3-hero"><div class="wrap"><div class="eyebrow">Autores Ediouro</div><h1>Uma biblioteca também é feita de vozes.</h1><p>Descubra quem escreve os livros do Grupo Ediouro e atravesse o catálogo por autores, séries e casas editoriais.</p><div class="authors-v3-search"><input placeholder="Busque um autor" aria-label="Buscar autor" oninput="filterAuthorsV3(this.value)"><button onclick="this.previousElementSibling.focus()">Buscar</button></div></div></section>
${featured.length?`<section class="authors-v3-featured"><div class="wrap"><div class="sec-head"><div><div class="eyebrow">Em destaque</div><h2>Autores para explorar</h2></div></div><div class="authors-v3-featured-grid"><article class="author-feature-main" onclick="go('/autores/${featured[0].a.slug}')"><div><div class="eyebrow" style="color:#bfb5dc">${featured[0].books.length} ${featured[0].books.length===1?'livro':'livros'} no catálogo</div><h2>${esc(featured[0].a.name)}</h2><p>${esc(authorBioV3(featured[0].a))}</p><div class="link" style="color:#fff;border-color:#fff;display:inline-block;margin-top:10px">Conhecer o autor</div></div><div class="author-orbit">${initials(featured[0].a.name)}</div></article><div class="author-feature-side">${featured.slice(1).map(({a,books})=>`<article class="author-feature-small" onclick="go('/autores/${a.slug}')"><div class="author-mini-mark">${initials(a.name)}</div><div><div class="eyebrow">${books.length} ${books.length===1?'livro':'livros'}</div><h3>${esc(a.name)}</h3><p>${esc(authorBioV3(a))}</p></div></article>`).join('')}</div></div></div></section>`:''}
<section class="authors-v3-index"><div class="wrap"><div class="authors-v3-index-head"><div><div class="eyebrow">Todos os autores</div><h2>De A a Z</h2></div><p>${list.length} nomes no catálogo integrado</p></div><div class="authors-v3-alpha">${letters.map(l=>`<button onclick="document.getElementById('author-letter-${l}')?.scrollIntoView({behavior:'smooth',block:'start'})">${esc(l)}</button>`).join('')}</div>${letters.map(l=>{const names=list.filter(a=>a.name?.[0]?.toUpperCase()===l);return `<div class="author-letter-block" id="author-letter-${l}" style="scroll-margin-top:95px"><div class="author-letter">${esc(l)}</div><div class="author-directory">${names.map(a=>{const books=authorBooksV3(a.slug);const impr=authorImprintsV3(books)[0];return `<article class="author-directory-card" data-search="${esc((a.name+' '+(impr?.im?.name||'')).toLowerCase())}" onclick="go('/autores/${a.slug}')"><h3>${esc(a.name)}</h3><span>${books.length} ${books.length===1?'livro':'livros'}${impr?' · '+esc(impr.im.name):''}</span></article>`}).join('')}</div></div>`}).join('')}</div></section></main>`}
function authorPage(slug){const a=C[slug];if(!a)return notFound();const books=authorLatestV3(authorBooksV3(slug));const imprints=authorImprintsV3(books);const mainIm=imprints[0]?.im||I.trama;const series=authorSeriesV3(books);const posts=authorPostsV3(books);const bio=authorAllBioV3(a);return `<main>
<section class="author-v3-hero"><div class="wrap author-v3-grid"><div class="author-v3-portrait" style="background:${mainIm?.color||'#17362f'};color:${mainIm?.ink||'#fff'}"><strong>${initials(a.name)}</strong></div><div class="author-v3-copy"><div class="eyebrow">Autor</div><h1>${esc(a.name)}</h1><div class="bio-lead">${esc(bio[0]||authorBioV3(a))}</div><div class="author-v3-meta"><div><strong>${books.length}</strong><span>${books.length===1?'livro':'livros'}</span></div>${series.length?`<div><strong>${series.length}</strong><span>${series.length===1?'série':'séries'}</span></div>`:''}<div><strong>${imprints.length}</strong><span>${imprints.length===1?'marca':'marcas'}</span></div></div><div class="author-v3-pills">${imprints.map(x=>`<span class="author-v3-pill" onclick="go('/marcas/${x.slug}')">${esc(x.im.name)} · ${x.count}</span>`).join('')}${series.map(s=>`<span class="author-v3-pill" onclick="go('/series/${s.slug}')">${esc(s.name)}</span>`).join('')}</div></div></div></section>
${bio.length>1?`<section style="padding:52px 0 0"><div class="narrow"><div class="eyebrow">Sobre o autor</div><div class="bodycopy">${bio.slice(1).map(p=>`<p>${esc(p)}</p>`).join('')}</div></div></section>`:''}
<section class="author-v3-books"><div class="wrap"><div class="sec-head"><div><div class="eyebrow">Bibliografia</div><h2>Livros de ${esc(a.name)}</h2></div><div class="result-summary">${books.length} ${books.length===1?'título':'títulos'}</div></div>${books.length?`<div class="catalog-grid">${books.map(bookCard).join('')}</div>`:`<div class="notice">Nenhum título integrado nesta prévia.</div>`}</div></section>
${series.length?`<section class="author-v3-series"><div class="wrap"><div class="sec-head"><div><div class="eyebrow" style="color:#a9a096">Séries e universos</div><h2>Histórias que continuam</h2></div></div><div class="author-v3-series-grid">${series.map(s=>{const sb=s.workSlugs.map(x=>W[x]).filter(Boolean);return `<article class="author-v3-series-card" onclick="go('/series/${s.slug}')"><div><div class="eyebrow" style="color:#aaa198">${sb.length} ${sb.length===1?'volume':'volumes'}</div><h3>${esc(s.name)}</h3><p>${esc(s.description||'')}</p><div class="link" style="color:#fff;border-color:#8d857c;display:inline-block">Ver ordem de leitura</div></div><div class="author-v3-series-covers">${sb.slice(0,3).map(w=>cover(w)).join('')}</div></article>`}).join('')}</div></div></section>`:''}
${posts.length?`<section class="author-v3-editorial"><div class="wrap"><div class="sec-head"><div><div class="eyebrow">Descubra</div><h2>Leia além dos livros</h2></div></div><div class="author-v3-editorial-grid"><article class="author-v3-editorial-feature" onclick="go('/descubra/${posts[0].slug}')"><div class="eyebrow" style="color:#f0c9d9">${esc(posts[0].kind)}</div><h2>${esc(posts[0].title)}</h2><p>${esc(posts[0].standfirst)}</p></article><div class="author-v3-editorial-stack">${posts.slice(1).map(p=>`<article class="author-v3-editorial-card" onclick="go('/descubra/${p.slug}')"><div class="eyebrow">${esc(p.kind)}</div><h3>${esc(p.title)}</h3><p>${esc(p.standfirst)}</p></article>`).join('')}</div></div></div></section>`:''}
</main>`}
