function countBy(list,key){const m={};list.forEach(x=>{const k=key(x);if(k)m[k]=(m[k]||0)+1});return m}
function qlink(path,label,count,active=false){return `<div class="filter-link ${active?'active':''}" onclick="go('${path}')"><span>${esc(label)}</span>${count!=null?`<span class="filter-count">${count}</span>`:''}</div>`}
function catalogSearchGo(){const el=document.getElementById('catalogSearch');if(!el)return;const p=new URLSearchParams((location.hash.split('?')[1]||'')),v=el.value.trim();if(v)p.set('q',v);else p.delete('q');location.hash='/livros'+(p.toString()?'?'+p.toString():'')}
function prettyTerm(s){const map={'crime-e-misterio':'Crime e mistério','fantasia':'Fantasia','romance':'Romance','literatura':'Literatura','thriller':'Thriller','ficcao-cientifica':'Ficção científica','livros-da-alice':'Livros da Alice'};if(map[s])return map[s];return String(s||'').replaceAll('-',' ').replace(/\b\w/g,m=>m.toUpperCase())}
function catalog(params){
 let q=(params.get('q')||'').trim(),marca=params.get('marca')||'',serie=params.get('serie')||'',categoria=params.get('categoria')||'',ordem=params.get('ordem')||'destaques',list=[...DATA.works];
 const low=q.toLowerCase();if(marca)list=list.filter(w=>w.imprint===marca);if(serie)list=list.filter(w=>w.series===serie);if(categoria)list=list.filter(w=>(w.categories||[]).includes(categoria));if(low)list=list.filter(w=>[w.title,w.shortDescription,authorNames(w),w.series?S[w.series]?.name:'',...(w.categories||[]),...(ED[w.slug]||[]).flatMap(e=>[e.isbn,e.ean])].join(' ').toLowerCase().includes(low));
 const pubDate=w=>(ED[w.slug]||[]).map(e=>e.publicationDate||'').sort().reverse()[0]||'';if(ordem==='az')list.sort((a,b)=>a.title.localeCompare(b.title,'pt-BR'));else if(ordem==='recentes')list.sort((a,b)=>pubDate(b).localeCompare(pubDate(a)));else if(ordem==='preco')list.sort((a,b)=>(principal(a).price??99999)-(principal(b).price??99999));else list.sort((a,b)=>(b.popularity||0)-(a.popularity||0)||a.title.localeCompare(b.title,'pt-BR'));
 const imprintCounts=countBy(DATA.works,w=>w.imprint),catCounts=countBy(DATA.works.flatMap(w=>(w.categories||[]).map(c=>({c}))),x=>x.c),categories=Object.keys(catCounts).sort((a,b)=>catCounts[b]-catCounts[a]).slice(0,12),seriesTop=DATA.series.slice().sort((a,b)=>b.workSlugs.length-a.workSlugs.length).slice(0,8);
 const makeUrl=(changes={})=>{const p=new URLSearchParams(params.toString());Object.entries(changes).forEach(([k,v])=>{if(v===null||v==='')p.delete(k);else p.set(k,v)});const s=p.toString();return '/livros'+(s?'?'+s:'')};
 const active=[];if(marca)active.push(`<span class="active-filter">${esc(I[marca]?.name||prettyTerm(marca))}<button onclick="event.stopPropagation();go('${makeUrl({marca:null})}')">×</button></span>`);if(serie)active.push(`<span class="active-filter">${esc(S[serie]?.name||prettyTerm(serie))}<button onclick="event.stopPropagation();go('${makeUrl({serie:null})}')">×</button></span>`);if(categoria)active.push(`<span class="active-filter">${esc(prettyTerm(categoria))}<button onclick="event.stopPropagation();go('${makeUrl({categoria:null})}')">×</button></span>`);if(q)active.push(`<span class="active-filter">“${esc(q)}”<button onclick="event.stopPropagation();go('${makeUrl({q:null})}')">×</button></span>`);
 const sortChip=(value,label)=>`<button class="sort-chip ${ordem===value?'active':''}" onclick="go('${makeUrl({ordem:value==='destaques'?null:value})}')">${label}</button>`,heading=q?`Resultados para “${esc(q)}”`:marca?esc(I[marca]?.name||prettyTerm(marca)):serie?esc(S[serie]?.name||prettyTerm(serie)):categoria?esc(prettyTerm(categoria)):'Todos os livros';
 return `<main class="catalog-v3"><div class="catalog-v3-hero"><div class="wrap"><div class="eyebrow">CATÁLOGO EDIOURO</div><div class="catalog-v3-title"><h1>Encontre seu próximo livro.</h1><p>Pesquise por título, autor, série ou ISBN. Depois atravesse o catálogo por marca, tema e universo.</p></div><div class="catalog-v3-search"><input value="${esc(q)}" id="catalogSearch" placeholder="Título, autor, série ou ISBN" onkeydown="if(event.key==='Enter')catalogSearchGo()"><button onclick="catalogSearchGo()">Buscar</button></div><div class="catalog-v3-shortcuts"><span>Explore:</span>${categories.slice(0,6).map(c=>`<button onclick="go('/livros?categoria=${encodeURIComponent(c)}')">${esc(prettyTerm(c))}</button>`).join('')}</div></div></div><section class="catalog-v3-body"><div class="wrap"><div class="catalog-mobile-filters"><button class="${!marca&&!categoria&&!serie?'active':''}" onclick="go('/livros')">Todos</button>${IMPRINTS.filter(im=>imprintCounts[im.slug]).map(im=>`<button class="${marca===im.slug?'active':''}" onclick="go('/livros?marca=${im.slug}')">${esc(im.name)}</button>`).join('')}${categories.slice(0,5).map(c=>`<button class="${categoria===c?'active':''}" onclick="go('/livros?categoria=${encodeURIComponent(c)}')">${esc(prettyTerm(c))}</button>`).join('')}</div><div class="catalog-shell"><aside class="catalog-aside"><div class="catalog-aside-title">Filtrar catálogo</div><div class="filter-group"><h4>Marcas</h4>${qlink('/livros','Todas',DATA.works.length,!marca&&!categoria&&!serie&&!q)}${IMPRINTS.filter(im=>imprintCounts[im.slug]).map(im=>qlink('/livros?marca='+im.slug,im.name,imprintCounts[im.slug]||0,marca===im.slug)).join('')}</div><div class="filter-group"><h4>Temas</h4>${categories.map(c=>qlink('/livros?categoria='+encodeURIComponent(c),prettyTerm(c),catCounts[c],categoria===c)).join('')}</div>${seriesTop.length?`<div class="filter-group"><h4>Séries</h4>${seriesTop.map(s=>qlink('/livros?serie='+encodeURIComponent(s.slug),s.name,s.workSlugs.length,serie===s.slug)).join('')}</div>`:''}</aside><div class="catalog-results"><div class="catalog-results-top"><div><div class="eyebrow">Catálogo</div><h2>${heading}</h2></div><div class="result-summary">${list.length} ${list.length===1?'título':'títulos'}</div></div>${active.length?`<div class="active-filters">${active.join('')}<button class="clear-filters" onclick="go('/livros')">Limpar tudo</button></div>`:''}<div class="catalog-sort"><span>Ordenar</span>${sortChip('destaques','Destaques')}${sortChip('recentes','Mais recentes')}${sortChip('az','A–Z')}${sortChip('preco','Menor preço')}</div>${list.length?`<div class="catalog-results-grid">${list.map(bookCard).join('')}</div>`:`<div class="catalog-empty"><div class="eyebrow">Nenhum resultado</div><h3>Esse caminho ainda não encontrou um livro.</h3><p>Tente outro título, autor, tema ou volte para o catálogo completo.</p><button onclick="go('/livros')">Ver todos os livros</button></div>`}</div></div></div></section></main>`}
