const supportPageBeforeSac = supportPage;
supportPage = function(type){
 if(type==='sac')return `<main><div class="support-hero blue"><div class="wrap"><div class="eyebrow">Atendimento ao leitor</div><h1>SAC</h1><p>Dúvidas sobre livros e produtos, problemas com exemplares, orientações sobre compras e outros assuntos de atendimento do Grupo Ediouro.</p></div></div><section><div class="wrap"><div class="support-intro-row"><div><div class="eyebrow">Fale com a Ediouro</div><h2>Vamos entender o que aconteceu.</h2></div><p>Nosso SAC centraliza o atendimento ao leitor para as marcas do Grupo Ediouro. Para facilitar o encaminhamento, conte qual é o livro ou produto, a marca responsável e o que você precisa resolver.</p></div><div class="support-contact-grid support-contact-grid-three">${supportEmailCard('Livros e produtos','Dúvidas e problemas com exemplares','Para dúvidas sobre conteúdo, edição, características do produto, defeitos físicos, itens ausentes ou outras questões relacionadas a livros e produtos do grupo.','sac@ediouro.com.br','SAC | Livro ou produto')}${supportEmailCard('Compras e pedidos','Orientação sobre compra, entrega ou troca','Se a compra foi feita diretamente com uma operação do Grupo Ediouro, envie os dados do pedido. Em compras feitas em livrarias ou marketplaces, questões de pagamento, entrega, cancelamento e devolução devem ser tratadas primeiro com a loja responsável.','sac@ediouro.com.br','SAC | Compra ou pedido')}<article class="support-contact-card"><div><div class="eyebrow">Acessibilidade</div><img src="https://raw.githubusercontent.com/thadeucupello/ediouro/main/preview/livro-acessivel.svg" alt="Livro Acessível" style="display:block;width:150px;max-width:100%;height:auto;margin:8px 0 18px"><p>Consulte o Portal do Livro Acessível para informações e orientações relacionadas ao serviço.</p></div><a class="support-email-cta" href="https://www.livroacessivel.org.br/" target="_blank" rel="noopener noreferrer"><span>Acessar o portal</span><span>↗</span></a></article></div><div class="support-note"><strong>Para agilizar o atendimento:</strong> informe título do livro ou nome do produto, ISBN ou EAN quando souber, marca ou selo, local da compra, número do pedido quando houver e uma descrição objetiva do problema. Fotos podem ajudar em casos de defeito ou avaria.</div><div class="support-note"><strong>Canal oficial:</strong> o atendimento público desta página é feito pelo e-mail <a href="mailto:sac@ediouro.com.br">sac@ediouro.com.br</a>. Outros canais só devem ser divulgados aqui depois de confirmação institucional.</div><div class="support-bottom-grid"><div><div class="eyebrow">Procura outra área?</div><h3>Cada assunto tem um caminho próprio.</h3><p>Imprensa, comercial, direitos autorais e privacidade têm canais específicos para chegar mais rápido ao time responsável.</p></div>${supportNavLinks([['Imprensa','/imprensa'],['Comercial','/comercial'],['Privacidade e LGPD','/privacidade']])}</div></div></section></main>`;
 return supportPageBeforeSac(type);
};

const footerBeforeSac = footer;
footer = function(){return `<footer class="footer"><div class="wrap footer-grid"><div><div class="logo" onclick="go('/')" style="cursor:pointer">Ediouro</div><p style="color:#bbb3a8;font-size:13px;line-height:1.6;max-width:260px">Livros, autores, séries e marcas do Grupo Ediouro.</p><div class="footer-contact"><span onclick="go('/sac')" style="cursor:pointer">Atendimento</span><a href="mailto:sac@ediouro.com.br">sac@ediouro.com.br</a></div><a class="accessible-book-badge official-accessible-logo" href="https://www.livroacessivel.org.br/" target="_blank" rel="noopener noreferrer" aria-label="Acessar o Portal do Livro Acessível"><img src="https://raw.githubusercontent.com/thadeucupello/ediouro/main/preview/livro-acessivel.svg" alt="Livro Acessível"></a></div><div><h4>Nossas marcas</h4><ul>${IMPRINTS.map(i=>`<li onclick="go('/marcas/${i.slug}')">${esc(i.name)}</li>`).join('')}</ul></div><div><h4>Descubra</h4><ul><li onclick="go('/livros')">Livros</li><li onclick="go('/autores')">Autores</li><li onclick="go('/series')">Séries</li><li onclick="go('/descubra')">Conteúdos</li></ul></div><div><h4>Ediouro</h4><ul><li onclick="go('/sobre')">Sobre</li><li onclick="go('/imprensa')">Imprensa</li><li onclick="go('/carreiras')">Carreiras</li><li onclick="go('/sac')">Atendimento</li><li onclick="go('/privacidade')">Privacidade</li></ul></div><div><h4>Parceiros</h4><ul><li onclick="go('/comercial')">Comercial</li><li onclick="go('/direitos-autorais')">Direitos autorais</li><li onclick="go('/projetos-especiais')">Projetos especiais</li><li onclick="go('/distribuicao')">Distribuição</li></ul></div></div></footer>`};

const routerBeforeSac = router;
router = function(){
 const raw=location.hash.slice(1)||'/',path=raw.split('?')[0];
 if(path==='/sac'||path==='/atendimento'){
  document.getElementById('app').innerHTML=header()+supportPage('sac')+footer();
  scrollTo(0,0);
  return;
 }
 return routerBeforeSac();
};
